### ISSUE TITLE
sensor v2 TODO

### ISSUE THREAD

**Issue by mysterywolf** [mysterywolf/rt-thread#2]
- [ ] _sensor_open 返回值错误码流程需要重新梳理
- [ ] 移除module，如果需要同时获取多个传感器数据，可以创建一个传感器组合作为一个新的传感器。
- [ ] 支持二级命令
- [ ] sensor 中断模式 - 直接上报用户回调函数，不做其他处理 or 是否还需要保留中断？直接使用pin设备框架的中断让用户自行处理？
